name: CD

on: 
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install
      run: npm i
    - name: Build 
      run: gulp css-vendors styles images html
    - name: Bundle
      run: mkdir ./out && mv dist out/xyz-my-plant
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: MemboLembo/MemboLembo.github.io
        publish_dir: ./out
        publish_branch: master
        keep_files: true
